# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelp', '0003_gdd'),
    ]

    operations = [
        migrations.AddField(
            model_name='spawningstreamlength',
            name='timestamp',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='gdd',
            name='timestamp',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='dischargedata',
            unique_together=set([('station_id', 'timestamp')]),
        ),
        migrations.AlterUniqueTogether(
            name='spawningstreamlength',
            unique_together=set([('station_id', 'timestamp')]),
        ),
        migrations.AlterUniqueTogether(
            name='watertemperature',
            unique_together=set([('station_id', 'timestamp')]),
        ),
    ]
